// Code generated by protoc-gen-go. DO NOT EDIT.
// source: users_service.proto

package core_grpc_api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName            string               `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string               `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Username             string               `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Email                string               `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Password             string               `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            *timestamp.Timestamp `protobuf:"bytes,9,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_e2683e726c16c873, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *User) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *User) GetDeletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

type CreateUserRequest struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e2683e726c16c873, []int{1}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *CreateUserRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *CreateUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CreateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type GetUserById struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserById) Reset()         { *m = GetUserById{} }
func (m *GetUserById) String() string { return proto.CompactTextString(m) }
func (*GetUserById) ProtoMessage()    {}
func (*GetUserById) Descriptor() ([]byte, []int) {
	return fileDescriptor_e2683e726c16c873, []int{2}
}

func (m *GetUserById) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserById.Unmarshal(m, b)
}
func (m *GetUserById) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserById.Marshal(b, m, deterministic)
}
func (m *GetUserById) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserById.Merge(m, src)
}
func (m *GetUserById) XXX_Size() int {
	return xxx_messageInfo_GetUserById.Size(m)
}
func (m *GetUserById) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserById.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserById proto.InternalMessageInfo

func (m *GetUserById) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type CreateUserReply struct {
	WasCreated           bool     `protobuf:"varint,1,opt,name=wasCreated,proto3" json:"wasCreated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserReply) Reset()         { *m = CreateUserReply{} }
func (m *CreateUserReply) String() string { return proto.CompactTextString(m) }
func (*CreateUserReply) ProtoMessage()    {}
func (*CreateUserReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_e2683e726c16c873, []int{3}
}

func (m *CreateUserReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserReply.Unmarshal(m, b)
}
func (m *CreateUserReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserReply.Marshal(b, m, deterministic)
}
func (m *CreateUserReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserReply.Merge(m, src)
}
func (m *CreateUserReply) XXX_Size() int {
	return xxx_messageInfo_CreateUserReply.Size(m)
}
func (m *CreateUserReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserReply proto.InternalMessageInfo

func (m *CreateUserReply) GetWasCreated() bool {
	if m != nil {
		return m.WasCreated
	}
	return false
}

func init() {
	proto.RegisterType((*User)(nil), "core.grpc.api.User")
	proto.RegisterType((*CreateUserRequest)(nil), "core.grpc.api.CreateUserRequest")
	proto.RegisterType((*GetUserById)(nil), "core.grpc.api.GetUserById")
	proto.RegisterType((*CreateUserReply)(nil), "core.grpc.api.CreateUserReply")
}

func init() {
	proto.RegisterFile("users_service.proto", fileDescriptor_e2683e726c16c873)
}

var fileDescriptor_e2683e726c16c873 = []byte{
	// 401 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x4f, 0xcf, 0xd2, 0x40,
	0x10, 0xc6, 0xd3, 0xbe, 0xd0, 0xb7, 0x1d, 0xfc, 0x13, 0x17, 0x63, 0x9a, 0x12, 0x90, 0xf4, 0xc4,
	0x69, 0x51, 0x3c, 0x18, 0xbd, 0xa1, 0x31, 0x44, 0x0f, 0x1e, 0xaa, 0x9e, 0xc9, 0xd2, 0x0e, 0xa4,
	0x49, 0x6b, 0xd7, 0xdd, 0xad, 0x84, 0x0f, 0xe3, 0x67, 0x32, 0x7e, 0x23, 0xb3, 0xbb, 0x6d, 0x02,
	0xe5, 0x05, 0x8e, 0x33, 0xcf, 0xf3, 0xeb, 0xce, 0x3c, 0x1d, 0x18, 0xd6, 0x12, 0x85, 0x5c, 0x4b,
	0x14, 0xbf, 0xf3, 0x14, 0x29, 0x17, 0x95, 0xaa, 0xc8, 0xe3, 0xb4, 0x12, 0x48, 0x77, 0x82, 0xa7,
	0x94, 0xf1, 0x3c, 0x7a, 0xb9, 0xab, 0xaa, 0x5d, 0x81, 0x73, 0x23, 0x6e, 0xea, 0xed, 0x5c, 0xe5,
	0x25, 0x4a, 0xc5, 0x4a, 0x6e, 0xfd, 0xd1, 0xa8, 0x6b, 0xc0, 0x92, 0xab, 0x83, 0x15, 0xe3, 0x7f,
	0x2e, 0xf4, 0x7e, 0x48, 0x14, 0xe4, 0x09, 0xb8, 0x79, 0x16, 0x3a, 0x53, 0x67, 0x16, 0x24, 0x6e,
	0x9e, 0x91, 0x31, 0xc0, 0x36, 0x17, 0x52, 0xad, 0x7f, 0xb2, 0x12, 0x43, 0xd7, 0xf4, 0x03, 0xd3,
	0xf9, 0xca, 0x4a, 0x24, 0x23, 0x08, 0x0a, 0xd6, 0xaa, 0x77, 0x46, 0xf5, 0x75, 0xc3, 0x88, 0x11,
	0xf8, 0x7a, 0x70, 0xa3, 0xf5, 0xac, 0xd6, 0xd6, 0xe4, 0x39, 0xf4, 0xb1, 0x64, 0x79, 0x11, 0xf6,
	0x8d, 0x60, 0x0b, 0x4d, 0x70, 0x26, 0xe5, 0xbe, 0x12, 0x59, 0xe8, 0x59, 0xa2, 0xad, 0xc9, 0x3b,
	0x80, 0x54, 0x20, 0x53, 0x98, 0xad, 0x99, 0x0a, 0xef, 0xa7, 0xce, 0x6c, 0xb0, 0x88, 0xa8, 0x5d,
	0x8a, 0xb6, 0x4b, 0xd1, 0xef, 0xed, 0xd6, 0x49, 0xd0, 0xb8, 0x97, 0x4a, 0xa3, 0x35, 0xcf, 0x5a,
	0xd4, 0xbf, 0x8d, 0x36, 0x6e, 0x8b, 0x66, 0x58, 0x60, 0x83, 0x06, 0xb7, 0xd1, 0xc6, 0xbd, 0x54,
	0xf1, 0x1f, 0x07, 0x9e, 0x7d, 0x34, 0x33, 0xe8, 0x64, 0x13, 0xfc, 0x55, 0xa3, 0x54, 0x9d, 0x40,
	0x9d, 0xab, 0x81, 0xba, 0x57, 0x02, 0xbd, 0xbb, 0x14, 0x68, 0xef, 0x52, 0xa0, 0xfd, 0xd3, 0x40,
	0xe3, 0x31, 0x0c, 0x56, 0xa8, 0xf4, 0x6c, 0x1f, 0x0e, 0x9f, 0xb3, 0xee, 0x9f, 0x8f, 0x5f, 0xc3,
	0xd3, 0xe3, 0xe9, 0x79, 0x71, 0x20, 0x13, 0x80, 0x3d, 0x93, 0xb6, 0x6b, 0xad, 0x7e, 0x72, 0xd4,
	0x59, 0xfc, 0x75, 0xe0, 0x91, 0x76, 0xcb, 0x6f, 0xf6, 0x52, 0xc9, 0x17, 0xf0, 0xac, 0x46, 0xa6,
	0xf4, 0xe4, 0x5c, 0xe9, 0x59, 0x30, 0xd1, 0xe4, 0x8a, 0x43, 0x3f, 0xfe, 0x16, 0xbc, 0x15, 0xaa,
	0x65, 0x51, 0x90, 0x17, 0x67, 0xf9, 0x7f, 0xd2, 0xa7, 0x1c, 0x0d, 0x3b, 0x5f, 0xd0, 0xec, 0x2b,
	0x87, 0xbc, 0x87, 0xfb, 0x15, 0x2a, 0xb3, 0x63, 0xd4, 0x71, 0x1c, 0xed, 0xff, 0x20, 0xbd, 0xf1,
	0xcc, 0x13, 0x6f, 0xfe, 0x07, 0x00, 0x00, 0xff, 0xff, 0x5d, 0x40, 0x88, 0xee, 0x82, 0x03, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// UsersServiceClient is the client API for UsersService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UsersServiceClient interface {
	Create(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserReply, error)
	GetAll(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (UsersService_GetAllClient, error)
	GetById(ctx context.Context, in *GetUserById, opts ...grpc.CallOption) (*User, error)
}

type usersServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUsersServiceClient(cc grpc.ClientConnInterface) UsersServiceClient {
	return &usersServiceClient{cc}
}

func (c *usersServiceClient) Create(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserReply, error) {
	out := new(CreateUserReply)
	err := c.cc.Invoke(ctx, "/core.grpc.api.UsersService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) GetAll(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (UsersService_GetAllClient, error) {
	stream, err := c.cc.NewStream(ctx, &_UsersService_serviceDesc.Streams[0], "/core.grpc.api.UsersService/GetAll", opts...)
	if err != nil {
		return nil, err
	}
	x := &usersServiceGetAllClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type UsersService_GetAllClient interface {
	Recv() (*User, error)
	grpc.ClientStream
}

type usersServiceGetAllClient struct {
	grpc.ClientStream
}

func (x *usersServiceGetAllClient) Recv() (*User, error) {
	m := new(User)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *usersServiceClient) GetById(ctx context.Context, in *GetUserById, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/core.grpc.api.UsersService/GetById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UsersServiceServer is the server API for UsersService service.
type UsersServiceServer interface {
	Create(context.Context, *CreateUserRequest) (*CreateUserReply, error)
	GetAll(*empty.Empty, UsersService_GetAllServer) error
	GetById(context.Context, *GetUserById) (*User, error)
}

// UnimplementedUsersServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUsersServiceServer struct {
}

func (*UnimplementedUsersServiceServer) Create(ctx context.Context, req *CreateUserRequest) (*CreateUserReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedUsersServiceServer) GetAll(req *empty.Empty, srv UsersService_GetAllServer) error {
	return status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}
func (*UnimplementedUsersServiceServer) GetById(ctx context.Context, req *GetUserById) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetById not implemented")
}

func RegisterUsersServiceServer(s *grpc.Server, srv UsersServiceServer) {
	s.RegisterService(&_UsersService_serviceDesc, srv)
}

func _UsersService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/core.grpc.api.UsersService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).Create(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_GetAll_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(empty.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UsersServiceServer).GetAll(m, &usersServiceGetAllServer{stream})
}

type UsersService_GetAllServer interface {
	Send(*User) error
	grpc.ServerStream
}

type usersServiceGetAllServer struct {
	grpc.ServerStream
}

func (x *usersServiceGetAllServer) Send(m *User) error {
	return x.ServerStream.SendMsg(m)
}

func _UsersService_GetById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).GetById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/core.grpc.api.UsersService/GetById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).GetById(ctx, req.(*GetUserById))
	}
	return interceptor(ctx, in, info, handler)
}

var _UsersService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "core.grpc.api.UsersService",
	HandlerType: (*UsersServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _UsersService_Create_Handler,
		},
		{
			MethodName: "GetById",
			Handler:    _UsersService_GetById_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetAll",
			Handler:       _UsersService_GetAll_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "users_service.proto",
}
